import { AlertTriangle, CheckCircle2, Mail, ShieldCheck, Ticket, UserRound, Wrench } from 'lucide-react'

import type { PortalAppearance, PreviewDevice, PreviewState } from '../types'
import { cssVars } from '../utils'

export function PublicPortalPreview({ appearance, device, state = 'initial', noticeTitle = 'Aviso do portal', noticeMessage = 'Comunicado visível para esta unidade.', maintenanceTitle = 'Portal em manutenção', maintenanceMessage = 'Estamos realizando ajustes para melhorar o acesso.' }: { appearance: PortalAppearance; device: PreviewDevice; state?: PreviewState; noticeTitle?: string; noticeMessage?: string; maintenanceTitle?: string; maintenanceMessage?: string }) {
  const isMaintenance = state === 'maintenance'
  const isReleased = state === 'released'
  const activeMethod = state === 'cpf' ? 'CPF' : state === 'email' || state === 'code-sent' ? 'Email' : 'Voucher'
  return <div className={`public-preview-frame ${device}`} style={cssVars(appearance)}><div className="public-preview-screen"><div className="portal-brand mini"><div className="portal-brand-mark">{appearance.logoUrl ? <img src={appearance.logoUrl} alt="" /> : <ShieldCheck />}</div><div><span className="portal-eyebrow">{appearance.bannerText}</span><strong>{appearance.establishmentName}</strong><p>{appearance.welcomeText}</p></div></div>{state === 'notice' ? <div className="preview-notice"><AlertTriangle /><div><strong>{noticeTitle}</strong><span>{noticeMessage}</span></div></div> : null}{isMaintenance ? <div className="preview-auth-card maintenance"><Wrench /><strong>{maintenanceTitle}</strong><p>{maintenanceMessage}</p></div> : isReleased ? <div className="preview-auth-card released"><CheckCircle2 /><strong>{appearance.successMessage}</strong><button className="primary" type="button">Continuar para Internet</button></div> : <div className="preview-auth-card"><strong>{appearance.networkName}</strong><div className="preview-tabs"><span className={activeMethod === 'Voucher' ? 'active' : ''}><Ticket /> Voucher</span><span className={activeMethod === 'CPF' ? 'active' : ''}><UserRound /> CPF</span><span className={activeMethod === 'Email' ? 'active' : ''}><Mail /> Email</span></div><div className="preview-input"><span>{state === 'code-sent' ? 'Código enviado para o email' : activeMethod}</span></div><label className="check preview-check"><input type="checkbox" checked readOnly /> Li e aceito os Termos de Uso.</label><button className="primary" type="button">{state === 'code-sent' ? 'Validar código' : 'Liberar acesso'}</button></div>}<p className="preview-terms">{appearance.termsText.slice(0, 180)}{appearance.termsText.length > 180 ? '...' : ''}</p></div></div>
}