export type NoticeType = 'INFO' | 'WARNING' | 'MAINTENANCE' | 'CRITICAL'
export type Notice = { id: string; type: NoticeType; title: string; message: string; startsAt?: string | null; endsAt?: string | null; site: string }
export type Maintenance = { enabled: boolean; active: boolean; scheduled: boolean; title: string; message: string; startsAt?: string | null; endsAt?: string | null; imageUrl: string; visualConfig: Record<string, unknown> }
export type PortalSettings = { logoUrl: string; primaryColor: string; bannerText: string; welcomeText: string; successMessage?: string; expiredMessage?: string; networkName: string; establishmentName: string; termsText: string; maintenanceMode: boolean; maintenance: Maintenance; notifications: Notice[]; expirationWarningMinutes: number[]; allowedAuthMethods: Method[] }
export type AuthResponse = { sessionId: string; authorized: boolean; authorizedAt: string; expiresAt: string; remainingSeconds: number; totalSeconds: number; sessionMinutes: number; nextCheckSeconds?: number }
export type EmailCodeResponse = { expiresAt: string }
export type SessionStatus = { status: string; authorized: boolean; authorizedAt?: string | null; expiresAt?: string | null; serverNow: string; remainingSeconds: number; remainingMinutes: number; totalSeconds: number; warningMessage?: string | null; warningMinutes?: number | null; ssid: string; nextCheckSeconds: number }
export type Dashboard = { onlineUsers: number; expiringIn30Minutes: number; expiringIn10Minutes: number; scheduledMaintenances: number; activeNotifications: number; sessionsEndedToday: number; averageSessionSeconds: number; vouchersAvailable: number }
export type DashboardDayPoint = { date: string; label: string; count: number }
export type DashboardMethodPoint = { method: Method; count: number }
export type DashboardLongestSession = { sessionId: string; label: string; site: string; method: string; durationSeconds: number }
export type DashboardChartsData = { connectionsByDay: DashboardDayPoint[]; bestDays: DashboardDayPoint[]; quietDays: DashboardDayPoint[]; authMethods: DashboardMethodPoint[]; longestSessions: DashboardLongestSession[]; periodDays: number }
export type PortalAppearance = { networkName: string; establishmentName: string; logoUrl: string; primaryColor: string; bannerText: string; welcomeText: string; successMessage: string; expiredMessage: string; termsText: string; authMethods: Method[]; updatedAt?: string | null }
export type PortalSiteAppearance = PortalAppearance & { siteId: string; siteName: string; enabled: boolean; hasOverride: boolean }
export type MaintenanceAdmin = { maintenanceEnabled: boolean; maintenanceActive: boolean; maintenanceScheduled: boolean; maintenanceTitle: string; maintenanceMessage: string; maintenanceStartAt?: string | null; maintenanceEndAt?: string | null; maintenanceImageUrl: string; maintenanceVisualConfig?: Record<string, unknown>; updatedAt?: string | null }
export type SystemHealth = { status: string; database: { status: string }; schema: { status: string; findings: string[]; alembicRevision?: string | null }; unifi: { status: string; sites: number; message: string }; smtp: { configured: boolean; host: string; port: number; from: string }; runtime: { environment: string; adminEmailMfaRequired: boolean; mediaPublicBaseUrl: string; publicBaseUrl: string; adminBaseUrl: string } }
export type AdminMe = { id: string; email: string; name: string; role: string; siteIds: string[]; canSelectAllSites: boolean }
export type AdminLoginChallenge = { mfaRequired: true; email: string; expiresAt: string }
export type AllowedSite = { siteId: string; name: string; allowed: boolean }
export type SiteNode = { name: string; siteId?: string; status: string; aps: number; connectedClients: number; sessions: number; allowed?: boolean; authMethods?: Method[] }
export type AdminNotice = Notice & { enabled: boolean; createdAt: string; updatedAt: string }
export type AuditEntry = { id: number; actorId: string; event: string; createdAt: string; targetId: string; targetType?: string; siteLabel?: string }
export type AuthAttemptRow = { id: number; method: string; success: boolean; reason: string; createdAt: string }
export type Voucher = { id: string; codeLabel: string; description: string; status: string; durationMinutes: number; site: string; siteId?: string; siteName?: string; enabled: boolean; usedCount: number; expiresAt?: string | null; maxDevices: number; dataLimitMb?: number | null; downloadLimit?: number | null; uploadLimit?: number | null; deviceLimit: number; isActive: boolean; revokedAt?: string | null; createdAt: string }
export type CreatedVoucherCode = { id: string; code: string; codeLabel: string; site: string; durationMinutes: number; expiresAt?: string | null }
export type VoucherBatchCreateResponse = { created: number; vouchers: CreatedVoucherCode[] }
export type AdminInviteResponse = { id: string; email: string; name: string; role: string; siteIds: string[]; expiresAt: string; acceptedAt?: string | null; revokedAt?: string | null; deliveryStatus: string; inviteUrl?: string | null }
export type AdminInviteValidateResponse = { email: string; name: string; role: string; expiresAt: string; siteIds: string[] }
export type ClientRow = Record<string, unknown>
export type AccessPoint = Record<string, unknown>
export type SensitiveSessionReveal = { sessionId: string; name: string; email: string; cpf: string; phone: string; revealedAt: string }
export type GuestSessionRow = { id: string; name?: string; clientMac: string; apMac?: string; ssid?: string; site?: string; method: string; status: string; createdAt: string; authorizedAt?: string | null; expiresAt?: string | null; disconnectedAt?: string | null; endedAt?: string | null; endedBy?: string; adminEndReason?: string; reauthRequiredAt?: string | null; reauthReason?: string; remainingSeconds: number; durationSeconds: number; canEndAccess: boolean; canRequireReauth?: boolean; canExtend?: boolean; canReauthorize?: boolean; canBlock?: boolean }
export type AdminUserRow = { id: string; name: string; email: string; role: string; status: string; mfa: string; siteIds?: string[]; canSelectAllSites?: boolean; createdAt: string; lastLogin?: string | null }
export type SessionOperationResponse = { status: string; unifiConfirmed: boolean; message: string; sessionId: string; operationState: string; blockId?: string | null; newSessionId?: string | null; expiresAt?: string | null }

export type Method = 'voucher' | 'cpf' | 'email'
export type Stage = 'idle' | 'validating' | 'authorizing' | 'confirming' | 'checking' | 'released' | 'error'
export type AdminSection = 'dashboard' | 'sessions' | 'visitors' | 'vouchers' | 'notices' | 'maintenance' | 'sites' | 'site-detail' | 'access-points' | 'admins' | 'audit' | 'portal' | 'portal-sites' | 'health' | 'settings'
export type SessionFilter = 'all' | 'online' | 'expiring-30' | 'expiring-10' | 'ended-today'
export type PreviewDevice = 'mobile' | 'tablet' | 'desktop'
export type PreviewState = 'initial' | 'voucher' | 'cpf' | 'email' | 'code-sent' | 'released' | 'maintenance' | 'notice'

export type MediaAsset = { id: string; assetType: string; originalFilename: string; contentType: string; byteSize: number; width: number; height: number; publicUrl: string; createdAt: string }
